### ISSUE TITLE
Finalize Demo Video 

### ISSUE THREAD

**Issue by Marwasel** [DIT113-V22/group-12#118]
**Tasks**
- [x] Includes a link to a Youtube video with a demo
- [x]  showcases the entire functionality of the product
- [x] explains the problem the system solves and its business potential
- [x] Includes any other technical or otherwise details that fit
